usr/lib/leechcraft/plugins/*leechcraft_poshuku.so
usr/share/leechcraft/translations/leechcraft_poshuku_ru_RU.qm
usr/share/leechcraft/translations/leechcraft_poshuku_uk_UA.qm
usr/share/leechcraft/translations/leechcraft_poshuku_ar.qm
usr/share/leechcraft/settings/poshukusettings.xml

usr/lib/leechcraft/plugins/*leechcraft_poshuku_cleanweb.so
usr/share/leechcraft/translations/leechcraft_poshuku_cleanweb*.qm
usr/share/leechcraft/settings/poshukucleanwebsettings.xml

usr/lib/leechcraft/plugins/*leechcraft_poshuku_fatape.so
usr/share/leechcraft/translations/leechcraft_poshuku_fatape*.qm
usr/share/leechcraft/settings/poshukufatapesettings.xml

usr/lib/leechcraft/plugins/*leechcraft_poshuku_filescheme.so
usr/share/leechcraft/translations/leechcraft_poshuku_filescheme*.qm

usr/lib/leechcraft/plugins/*leechcraft_poshuku_fua.so
usr/share/leechcraft/translations/leechcraft_poshuku_fua*.qm
usr/share/leechcraft/settings/poshukufuasettings.xml

usr/lib/leechcraft/plugins/*leechcraft_poshuku_onlinebookmarks.so
usr/share/leechcraft/translations/leechcraft_poshuku_onlinebookmarks*.qm
usr/share/leechcraft/settings/poshukuonlinebookmarkssettings.xml

usr/lib/leechcraft/plugins/*leechcraft_poshuku_wyfv.so
usr/share/leechcraft/translations/leechcraft_poshuku_wyfv*.qm
usr/share/leechcraft/settings/poshukuwyfvsettings.xml
